### ISSUE TITLE
mupdf: cannot open gui: No such file or directory

### ISSUE THREAD

**Issue by retsyo** [dothinking/pdf2docx#100]
已经是pip最新版的fire，python setup.py安装的pdf2docx，及pymupdf页面最新的fitz

命令行方式，pdf2docx可以正常转换pdf到docx
但是，试图打开gui失败；而且，我没看懂mupdf到底要打开谁？
```
E:\prg\py\Anaconda3_64\Scripts>py3 pdf2docx-script.py gui
mupdf: cannot open gui: No such file or directory
Traceback (most recent call last):
  File "pdf2docx-script.py", line 33, in <module>
    sys.exit(load_entry_point('pdf2docx===alpha', 'console_scripts', 'pdf2docx')())
  File "e:\prg\py\Anaconda3_64\lib\site-packages\pdf2docx\main.py", line 67, in main
    fire.Fire(parse)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\pdf2docx\main.py", line 19, in parse
    cv = Converter(pdf_file, docx_file)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\pdf2docx\converter.py", line 31, in __init__
    self._doc_pdf = fitz.Document(pdf_file)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\fitz\fitz.py", line 3608, in __init__
    filename, stream, filetype, rect, width, height, fontsize
RuntimeError: cannot open gui: No such file or directory
```

**Comment by dothinking** [comment]
确实很奇怪，我试了以下两种命令行方式都没问题：

```
pdf2docx gui
```

```
python pdf2docx-script.py gui
```

我看你的`pdf2docx-script.py`至少33行，而我只有短短10行左右，可以看看其中的内容吗？

**Comment by retsyo** [comment]
E:\prg\py\Anaconda3_64\Scripts\下面的 pdf2docx-script.py 和 pdf2docx.exe，都是`python setup.py install`之后自动产生的，实际上 pdf2docx.exe 也就是调用 python 解释器去执行 pdf2docx-script.py 

pdf2docx-script.py 的内容为
```python
#!e:\prg\py\Anaconda3_64\python.exe
# EASY-INSTALL-ENTRY-SCRIPT: 'pdf2docx===alpha','console_scripts','pdf2docx'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'pdf2docx===alpha'

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point


def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()


globals().setdefault('load_entry_point', importlib_load_entry_point)


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('pdf2docx===alpha', 'console_scripts', 'pdf2docx')())

```

**Comment by dothinking** [comment]
嗯，那这个文件应该没问题。你用`setup.py`安装用的是哪个分支的代码？看一下这个文件呢：

e:\prg\py\Anaconda3_64\lib\site-packages\pdf2docx\main.py

**Comment by retsyo** [comment]
没问题了
