### ISSUE TITLE
pdf转word显示ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

### ISSUE THREAD

**Issue by chengtingting980903** [dothinking/pdf2docx#126]
代码
from pdf2docx import Converter
con = Converter(r'The-morphology-of-the-Arrival-City---A-global-categorization-_2018_Applied-G.pdf')
con.convert(r'The-morphology-of-the-Arrival-City---A-global-categorization-_2018_Applied-G1.docx')
con.close()

错误信息：
Traceback (most recent call last):
  File "D:/working/中科软项目/app/test.py", line 73, in <module>
    con.convert(r'C:\Users\EDZ\Desktop\The-morphology-of-the-Arrival-City---A-global-categorization-_2018_Applied-G1.docx')
  File "D:\software\anaconda3\envs\venv\lib\site-packages\pdf2docx\converter.py", line 305, in convert
    .make_docx(docx_filename)
  File "D:\software\anaconda3\envs\venv\lib\site-packages\pdf2docx\converter.py", line 186, in make_docx
    docx_file.save(filename)
  File "D:\software\anaconda3\envs\venv\lib\site-packages\docx\document.py", line 135, in save
    self._part.save(path_or_stream)
  File "D:\software\anaconda3\envs\venv\lib\site-packages\docx\parts\document.py", line 111, in save
    self.package.save(path_or_stream)
  File "D:\software\anaconda3\envs\venv\lib\site-packages\docx\opc\package.py", line 172, in save
    PackageWriter.write(pkg_file, self.rels, self.parts)
  File "D:\software\anaconda3\envs\venv\lib\site-packages\docx\opc\pkgwriter.py", line 35, in write
    PackageWriter._write_parts(phys_writer, parts)
  File "D:\software\anaconda3\envs\venv\lib\site-packages\docx\opc\pkgwriter.py", line 56, in _write_parts
    phys_writer.write(part.partname.rels_uri, part._rels.xml)
  File "D:\software\anaconda3\envs\venv\lib\site-packages\docx\opc\rel.py", line 83, in xml
    rel.rId, rel.reltype, rel.target_ref, rel.is_external
  File "D:\software\anaconda3\envs\venv\lib\site-packages\docx\opc\oxml.py", line 218, in add_rel
    relationship = CT_Relationship.new(rId, reltype, target, target_mode)
  File "D:\software\anaconda3\envs\venv\lib\site-packages\docx\opc\oxml.py", line 169, in new
    relationship.set('Target', target)
  File "src\lxml\etree.pyx", line 816, in lxml.etree._Element.set
  File "src\lxml\apihelpers.pxi", line 593, in lxml.etree._setAttributeValue
  File "src\lxml\apihelpers.pxi", line 1540, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

Process finished with exit code 1

**Comment by dothinking** [comment]
> ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

从错误信息来看，PDF文本中存在诸如`\x04`之类控制字符，导致使用`python-docx`库写入Word文件时出错。因此，修复方法为检测并过滤掉这些控制字符（不会影响正常文字结果显示）。

目前已在开发分支中修复，稍后随`v0.5.3`版本发布。

控制字符检测方法参考链接：

https://stackoverflow.com/questions/4324790/removing-control-characters-from-a-string-in-python

**Comment by dothinking** [comment]
更新：**lxml并非不能支持所有控制字符**，例如制表符`\t`是控制字符，但是可以正常显示。所以需要剔除掉控制字符中被`lxml`所支持的部分。

如何判断是否被支持？简单直接的方法——看`python-docx`库是否报错。

举个例子，验证`\t`和`\x04`：

```python
>>> from docx import Document
>>> doc = Document()

>>> doc.add_paragraph('\t')
<docx.text.paragraph.Paragraph object at 0x000001D87E9F56D8> # OK

>>> doc.add_paragraph('\x04')
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

于是准备一个验证函数：

```python
def lxml_supported_char(doc, ch):
    try:
        doc.add_paragraph(ch)
    except:
        return False
    else:
        return True
```

然后初始化所有**控制字符**：

```python
>>> import sys
>>> import unicodedata
>>> all_chars = [chr(i) for i in range(sys.maxunicode)]  # all characters
>>> len(all_chars)
1114111
>>> control_chars = ''.join(c for c in all_chars if unicodedata.category(c) == 'Cc')
>>> len(control_chars)
65
```

最后过滤出不支持的字符：

```python
>>> invalid_chars = ''.join(c for c in control_chars if not lxml_supported_char(doc,c))
>>> invalid_chars
'\x00\x01\x02\x03\x04\x05\x06\x07\x08\x0b\x0c\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f'
>>>
```

**Comment by dothinking** [comment]
新版已发布，关闭问题。
