### ISSUE TITLE
Calculate Cover Page Margin Error

### ISSUE THREAD

**Issue by dothinking** [dothinking/pdf2docx#13]
Below error shows when processing a cover page, i.e. a background picture covers the entire page
```
Traceback (most recent call last):
  File "d:\21_GitHub\pdf2docx\test\local_test.py", line 30, in <module>
    docx.make_page(layout)
  File "d:\21_GitHub\pdf2docx\pdf2docx\writer.py", line 17, in make_page
    docx.make_page(self._doc, layout)
  File "d:\21_GitHub\pdf2docx\pdf2docx\docx.py", line 50, in make_page
    section.right_margin = Pt(right)
  File "D:\89_Program_Files\Python368\lib\site-packages\docx\section.py", line 234, in right_margin
    self._sectPr.right_margin = value
  File "D:\89_Program_Files\Python368\lib\site-packages\docx\oxml\section.py", line 292, in right_margin
    pgMar.right = value
  File "D:\89_Program_Files\Python368\lib\site-packages\docx\oxml\xmlchemy.py", line 192, in set_attr_value
    str_value = self._simple_type.to_xml(value)
  File "D:\89_Program_Files\Python368\lib\site-packages\docx\oxml\simpletypes.py", line 25, in to_xml
    cls.validate(value)
  File "D:\89_Program_Files\Python368\lib\site-packages\docx\oxml\simpletypes.py", line 185, in validate
    cls.validate_int_in_range(value, 0, 18446744073709551615)
  File "D:\89_Program_Files\Python368\lib\site-packages\docx\oxml\simpletypes.py", line 42, in validate_int_in_range
    (min_inclusive, max_inclusive, value)
ValueError: value must be in range 0 to 18446744073709551615 inclusive, got -161543
```

**Comment by dothinking** [comment]
The root cause is negative page margin is calculated, so error when creating document with python-docx.
