### ISSUE TITLE
在测试出现     Ignore page %d due to making page error

### ISSUE THREAD

**Issue by huangzhiyong-xbadge** [dothinking/pdf2docx#134]
在测试文件时，发现这个问题，我尝试让它抛出实际一场位置，感觉应该是部分无框线表格中的有不规整的矩阵的问题吧。

`Traceback (most recent call last):
  File "D:/python_job/3.6/pythonProject/pdf2docx_test_demo.py", line 84, in <module>
    pdf2docx_f(pdf_file=pdf_file, docx_file=docx_file)
  File "D:/python_job/3.6/pythonProject/pdf2docx_test_demo.py", line 36, in pdf2docx_f
    cv.convert(docx_file)  # ,multi_processing=True)  # 默认参数start=0, end=None
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\converter.py", line 329, in convert
    self.parse(start, end, pages, **settings).make_docx(docx_filename, **settings)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\converter.py", line 203, in make_docx
    page.make_docx(docx_file)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\page\Page.py", line 202, in make_docx
    self.sections.make_docx(doc)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\layout\Sections.py", line 55, in make_docx
    section.make_docx(doc)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\layout\Section.py", line 97, in make_docx
    column.make_docx(doc)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\layout\Column.py", line 73, in make_docx
    self.blocks.make_docx(doc)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\layout\Blocks.py", line 333, in make_docx
    make_table(block, pre_table)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\layout\Blocks.py", line 318, in make_table
    table_block.make_docx(table)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\table\TableBlock.py", line 174, in make_docx
    self._rows[idx_row].make_docx(table, idx_row)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\table\Row.py", line 75, in make_docx
    self._cells[idx_col].make_docx(table, (idx_row, idx_col))
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\table\Cell.py", line 74, in make_docx
    self._set_style(table, indexes)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\table\Cell.py", line 134, in _set_style
    docx.set_cell_border(table.cell(m, n), **kwargs)        
  File "E:\Program Files\Python3.6.4\lib\site-packages\docx\table.py", line 81, in cell
    return self._cells[cell_idx]
IndexError: list index out of range`

`Traceback (most recent call last):
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\common\Collection.py", line 22, in __getitem__
    instances = self._instances[idx]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

·Traceback (most recent call last):
  File "D:/python_job/3.6/pythonProject/pdf2docx_test_demo.py", line 84, in <module>
    pdf2docx_f(pdf_file=pdf_file, docx_file=docx_file)
  File "D:/python_job/3.6/pythonProject/pdf2docx_test_demo.py", line 36, in pdf2docx_f
    cv.convert(docx_file)  # ,multi_processing=True)  # 默认参数start=0, end=None
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\converter.py", line 329, in convert
    self.parse(start, end, pages, **settings).make_docx(docx_filename, **settings)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\converter.py", line 203, in make_docx
    page.make_docx(docx_file)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\page\Page.py", line 202, in make_docx
    self.sections.make_docx(doc)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\layout\Sections.py", line 55, in make_docx
    section.make_docx(doc)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\layout\Section.py", line 97, in make_docx
    column.make_docx(doc)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\layout\Column.py", line 73, in make_docx
    self.blocks.make_docx(doc)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\layout\Blocks.py", line 333, in make_docx
    make_table(block, pre_table)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\layout\Blocks.py", line 318, in make_table
    table_block.make_docx(table)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\table\TableBlock.py", line 174, in make_docx
    self._rows[idx_row].make_docx(table, idx_row)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\table\Row.py", line 75, in make_docx
    self._cells[idx_col].make_docx(table, (idx_row, idx_col))
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\common\Collection.py", line 25, in __getitem__
    raise IndexError(msg)
IndexError: Collection index 2 out of range.`

`Traceback (most recent call last):
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\common\Collection.py", line 22, in __getitem__
    instances = self._instances[idx]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/python_job/3.6/pythonProject/pdf2docx_test_demo.py", line 84, in <module>
    pdf2docx_f(pdf_file=pdf_file, docx_file=docx_file)
  File "D:/python_job/3.6/pythonProject/pdf2docx_test_demo.py", line 36, in pdf2docx_f
    cv.convert(docx_file)  # ,multi_processing=True)  # 默认参数start=0, end=None
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\converter.py", line 329, in convert
    self.parse(start, end, pages, **settings).make_docx(docx_filename, **settings)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\converter.py", line 203, in make_docx
    page.make_docx(docx_file)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\page\Page.py", line 202, in make_docx
    self.sections.make_docx(doc)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\layout\Sections.py", line 55, in make_docx
    section.make_docx(doc)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\layout\Section.py", line 97, in make_docx
    column.make_docx(doc)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\layout\Column.py", line 73, in make_docx
    self.blocks.make_docx(doc)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\layout\Blocks.py", line 333, in make_docx
    make_table(block, pre_table)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\layout\Blocks.py", line 318, in make_table
    table_block.make_docx(table)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\table\TableBlock.py", line 174, in make_docx
    self._rows[idx_row].make_docx(table, idx_row)
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\table\Row.py", line 75, in make_docx
    self._cells[idx_col].make_docx(table, (idx_row, idx_col))
  File "E:\Program Files\Python3.6.4\lib\site-packages\pdf2docx\common\Collection.py", line 25, in __getitem__
    raise IndexError(msg)
IndexError: Collection index 5 out of range.`

**Comment by huangzhiyong-xbadge** [comment]
python 3.6.4 下 pymupdf 只能正常安装到1.19.3，3.8也试过如此，尚未在3.7及以上去测试。

**Comment by huangzhiyong-xbadge** [comment]
![docx](https://user-images.githubusercontent.com/81542591/167248971-fa56213e-e9c7-4129-b20e-8c8d673f5136.png)
![pdf](https://user-images.githubusercontent.com/81542591/167248973-d7317a87-051d-4619-8969-4bf548eb72a5.png)
