### ISSUE TITLE
'Page' object has no attribute 'rotationMatrix'

### ISSUE THREAD

**Issue by srszzw** [dothinking/pdf2docx#143]
Traceback (most recent call last):
  File "d:/temp/pdf2doc/pdf2doc.py", line 8, in <module>
    cv.convert(docx_file)      # all pages by default
  File "D:\anaconda\envs\pdf2doc\lib\site-packages\pdf2docx\converter.py", line 328, in convert
    self.parse(start, end, pages, **settings).make_docx(docx_filename, **settings)
  File "D:\anaconda\envs\pdf2doc\lib\site-packages\pdf2docx\converter.py", line 112, in parse
    .parse_document(**kwargs) \
  File "D:\anaconda\envs\pdf2doc\lib\site-packages\pdf2docx\converter.py", line 152, in parse_document
    self._pages.parse(self.fitz_doc, **kwargs)
  File "D:\anaconda\envs\pdf2doc\lib\site-packages\pdf2docx\page\Pages.py", line 36, in parse
    raw_page.restore(**settings)
  File "D:\anaconda\envs\pdf2doc\lib\site-packages\pdf2docx\common\share.py", line 226, in inner
    objects = func(*args, **kwargs)
  File "D:\anaconda\envs\pdf2doc\lib\site-packages\pdf2docx\page\RawPage.py", line 74, in restore
    raw_dict = self.extract_raw_dict(**settings)
  File "D:\anaconda\envs\pdf2doc\lib\site-packages\pdf2docx\page\RawPage.py", line 279, in extract_raw_dict
    Element.set_rotation_matrix(self.fitz_page.rotationMatrix)
AttributeError: 'Page' object has no attribute 'rotationMatrix'

**need to delete this line in the file RawPage.py：
Element.set_rotation_matrix(self.fitz_page.rotationMatrix)
then the code can run successfully**

**Comment by dothinking** [comment]
Same issue with #139 and #141. 

Please apply the fix manually, or just upgrade `pdf2docx` to v0.5.4.

```
pip install pdf2docx --upgrade
```

**Comment by wlevene** [comment]
pdf2document.com - No loss of pdf layout
30 free page conversions daily for all users.
