### ISSUE TITLE
KeyError: 'closePath'

### ISSUE THREAD

**Issue by XCR16729438** [dothinking/pdf2docx#146]
Env: python 3.10.4, pdf2docx 0.5.4, pymupdf 1.20.1
Test File: [https://arxiv.org/pdf/2201.10700.pdf](https://arxiv.org/pdf/2201.10700.pdf) (renamed by '5.pdf')
Test Code: (as Example 1 in QuickStart)
```
from pdf2docx import Converter

pdf_file = '5.pdf'
docx_file = '5.docx'

# convert pdf to docx
cv = Converter(pdf_file)
cv.convert(docx_file)      # all pages by default
cv.close()
```
Test Result:
Error report as
```
[INFO] Start to convert 5.pdf
[INFO] [1/4] Opening document...  
[INFO] [2/4] Analyzing document...
Traceback (most recent call last):
  File "d:\Files\Study\202206_202208\Python\HW2.1\test1.py", line 8, in <module>
    cv.convert(docx_file)      # all pages by default
  File "D:\Programs\anaconda3\envs\Test1\lib\site-packages\pdf2docx\converter.py", line 329, in convert       
    self.parse(start, end, pages, **settings).make_docx(docx_filename, **settings)
  File "D:\Programs\anaconda3\envs\Test1\lib\site-packages\pdf2docx\converter.py", line 112, in parse
    return self.load_pages(start, end, pages) \
  File "D:\Programs\anaconda3\envs\Test1\lib\site-packages\pdf2docx\converter.py", line 153, in parse_document
    self._pages.parse(self.fitz_doc, **kwargs)
  File "D:\Programs\anaconda3\envs\Test1\lib\site-packages\pdf2docx\page\Pages.py", line 37, in parse
    raw_page.restore(**settings)
  File "D:\Programs\anaconda3\envs\Test1\lib\site-packages\pdf2docx\common\share.py", line 226, in inner
    objects = func(*args, **kwargs)
  File "D:\Programs\anaconda3\envs\Test1\lib\site-packages\pdf2docx\page\RawPage.py", line 66, in restore
    raw_dict = self.extract_raw_dict(**settings)
  File "D:\Programs\anaconda3\envs\Test1\lib\site-packages\pdf2docx\page\RawPageFitz.py", line 35, in extract_raw_dict
    shapes, images =  self._preprocess_shapes(**settings)
  File "D:\Programs\anaconda3\envs\Test1\lib\site-packages\pdf2docx\page\RawPageFitz.py", line 113, in _preprocess_shapes
    paths = self._init_paths(**settings)
  File "D:\Programs\anaconda3\envs\Test1\lib\site-packages\pdf2docx\common\share.py", line 226, in inner
    objects = func(*args, **kwargs)
  File "D:\Programs\anaconda3\envs\Test1\lib\site-packages\pdf2docx\page\RawPageFitz.py", line 126, in _init_paths
    return Paths(parent=self).restore(raw_paths)
  File "D:\Programs\anaconda3\envs\Test1\lib\site-packages\pdf2docx\shape\Paths.py", line 27, in restore
    path = Path(raw)
  File "D:\Programs\anaconda3\envs\Test1\lib\site-packages\pdf2docx\shape\Path.py", line 246, in __init__
    close_path = True if self.is_fill else raw['closePath']
KeyError: 'closePath' 
```

P.S. I tried several similar papers, it seems that this error happenned when I tried very long files.

**Comment by N0I0C0K** [comment]
Yeah, i meet this problem too. 
But, I find a temporary method. (unreliable

**Comment by N0I0C0K** [comment]
I have the same problem
I had this problem converting a 90 page PDF.
But, I find a temporary method.（unreliable， Not official
change the file `[python install path]\site-packages\pdf2docx\shape\Path.py` line 246, in  \__init\__
` close_path = True if self.is_fill else raw['closePath']` => ` close_path = True #if self.is_fill else raw['closePath']`

## Remember to uncomment after use to avoid unexpected errors

**Comment by XCR16729438** [comment]
> I have the same problem I had this problem converting a 90 page PDF. But, I find a temporary method.（unreliable， Not official change the file `[python install path]\site-packages\pdf2docx\shape\Path.py` line 246, in __init__ ` close_path = True if self.is_fill else raw['closePath']` => ` close_path = True #if self.is_fill else raw['closePath']`
> 
> ## Remember to uncomment after use to avoid unexpected errors

That's effective, I have got the docx. file(with some format error but not important).

**Comment by Brand2** [comment]
This is definitely the source of the error. The more complete fix would be:

```python
close_path = True if self.is_fill else raw.get('closePath', True)
```

This respects the "default" provided to the `canvas.finish` called at the bottom of the `Path` class. I suppose `False` is just as good a default, but worth noting.

**Comment by dothinking** [comment]
@XCR16729438 Many thanks for reporting this issue and especially providing the sample file.

**Comment by dothinking** [comment]
The root cause is a minor update from the upstream library `PyMuPDF>=1.20`  -> in some cases, the property `closePath` seems not included for a stroke path when using [`page.get_cdrawings()`](https://pymupdf.readthedocs.io/en/latest/page.html#Page.get_cdrawings). 

@Brand2 thanks for your fix, and, I prefer the "default" to `False`, too. Will update the default value in `canvas.finish` as well.

```
close_path = True if self.is_fill else raw.get('closePath', False)
```

**Comment by NickMao-hub** [comment]
Hope to optimize as soon as possible, I also encountered this problem。thank！！

**Comment by dothinking** [comment]
Version `0.5.5` was released to resolve this issue.

```
pip install pdf2docx --upgrade
```
