### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by shinhanhwcho** [dothinking/pdf2docx#40]
Hello.

I tried to use pdf2docx.
When I try to  .pdf with Korean language to docx, I met some errors.

Here is the error message.
--------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:/insu_mrc/insu_terms_comparision/pdftohtmltest.py", line 45, in <module>
    print(cv.parse(page))
  File "C:\Users\19021003\AppData\Local\Programs\Python\Python37\lib\site-packages\pdf2docx\converter.py", line 112, in parse
    self.init(page).parse(**self._debug_kwargs)
  File "C:\Users\19021003\AppData\Local\Programs\Python\Python37\lib\site-packages\pdf2docx\layout\Layout.py", line 153, in parse
    self.parse_implicit_tables(**kwargs)
  File "C:\Users\19021003\AppData\Local\Programs\Python\Python37\lib\site-packages\pdf2docx\common\utils.py", line 148, in inner
    res = func(*args, **kwargs)
  File "C:\Users\19021003\AppData\Local\Programs\Python\Python37\lib\site-packages\pdf2docx\layout\Layout.py", line 278, in parse_implicit_tables
    tables = self._tables_constructor.implicit_tables(X0, X1)
  File "C:\Users\19021003\AppData\Local\Programs\Python\Python37\lib\site-packages\pdf2docx\table\TablesConstructor.py", line 85, in implicit_tables
    table_rects = self._implicit_borders(table_bboxes, X0, X1)
  File "C:\Users\19021003\AppData\Local\Programs\Python\Python37\lib\site-packages\pdf2docx\table\TablesConstructor.py", line 510, in _implicit_borders
    inner_borders = self._borders_from_bboxes(rects, border_bbox)
  File "C:\Users\19021003\AppData\Local\Programs\Python\Python37\lib\site-packages\pdf2docx\table\TablesConstructor.py", line 547, in _borders_from_bboxes
    cols_rects = self._column_borders_from_bboxes(rects)
  File "C:\Users\19021003\AppData\Local\Programs\Python\Python37\lib\site-packages\pdf2docx\table\TablesConstructor.py", line 604, in _column_borders_from_bboxes
    cols_rects[-1].append(rect)
IndexError: list index out of range
--------------------------------------------------------------------------------------------------------------------------------------------

If you are okay, I want to send some files to you for debugging.
Could you let me know your e-mail address?

**Comment by dothinking** [comment]
yes, please, thank you. train8808@gmail.com

**Comment by dothinking** [comment]
This issue occurs when processing zero-margin page. It was fixed, and combined with impartments like nested table based on your provided test files, version `0.4.0` is released. Please upgrade your installation and have a try:

```python
pip install pdf2docx --upgrade
```
