### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by MrSubmissive** [dothinking/pdf2docx#61]
Hello I use your documentation code but I think it has a problem about your module
I get this error again and again...
I get this error when the script get to my 3 pdf page
Processing Pages: 2/3...Traceback (most recent call last):
`
  File "m.py", line 8, in <module>
    parse(pdf_file, docx_file, start=0, end=3)
  File "/home/submissive/.local/lib/python3.6/site-packages/pdf2docx/main.py", line 31, in parse
    cv.make_docx(indexes, multi_processing)
  File "/home/submissive/.local/lib/python3.6/site-packages/pdf2docx/converter.py", line 117, in make_docx
    self._make_docx(page_indexes)
  File "/home/submissive/.local/lib/python3.6/site-packages/pdf2docx/converter.py", line 191, in _make_docx
    self.initialize(page).parse().make_page(self.doc_docx)
  File "/home/submissive/.local/lib/python3.6/site-packages/pdf2docx/converter.py", line 171, in initialize
    images, paths = self._paths_extractor.extract_paths(page)
  File "/home/submissive/.local/lib/python3.6/site-packages/pdf2docx/shape/Path.py", line 73, in extract_paths
    if largest.contains_curve(constants.FACTOR_A_FEW):
  File "/home/submissive/.local/lib/python3.6/site-packages/pdf2docx/shape/Path.py", line 128, in contains_curve
    return bbox.getArea()/self.bbox.getArea() >= ratio
ZeroDivisionError: float division by zero
`

Please Help me ❤️

**Comment by dothinking** [comment]
Yes, it's a known issue in `v0.4.6`, didn't get time to publish a new version yet. 

Could you please try a local fix:

Replace line 128 in "/home/submissive/.local/lib/python3.6/site-packages/pdf2docx/shape/Path.py"

```python
return bbox.getArea()/self.bbox.getArea() >= ratio
```

with

```python
return bbox.getArea()/self.bbox.getArea() >= ratio if self.bbox.getArea() else False
```

Thank you for reporting this. :)

**Comment by dothinking** [comment]
A new version `v0.5.0` was released for fixing some known issues.

```bash
pip install --upgrade pdf2docx
```
